/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_logic_solver_SatSolver */

#ifndef _Included_com_logic_solver_SatSolver
#define _Included_com_logic_solver_SatSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_logic_solver_SatSolver
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_logic_solver_SatSolver_init
  (JNIEnv *, jobject);

/*
 * Class:     com_logic_solver_SatSolver
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_logic_solver_SatSolver_reset
  (JNIEnv *, jobject);

/*
 * Class:     com_logic_solver_SatSolver
 * Method:    add_clause
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_logic_solver_SatSolver_add_1clause
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_logic_solver_SatSolver
 * Method:    assume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_logic_solver_SatSolver_assume
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_logic_solver_SatSolver
 * Method:    solve
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_logic_solver_SatSolver_solve
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
